language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 7.1
    - nightly
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
        - php: hhvm

install:
    - export PATH="$PATH:$HOME/.composer/vendor/bin"
    - composer tools
    - composer global require satooshi/php-coveralls ^1.0.0
    - composer update --no-interaction

before_script:
    - if php -v | grep -q 'Xdebug'; then coverage="--coverage-xml"; fi
    - vendor/bin/codecept build

script:
    - "! (composer outdated --direct | grep ^)"
    - vendor-tools/bin/php-cs-fixer fix --dry-run
    - vendor-tools/bin/phpstan analyse --level=7 --configuration=phpstan.neon src tests
    - vendor/bin/codecept run $coverage

after_success:
    - if [[ ! -z $coverage ]]; then coveralls; fi
